# Generated by Django 4.1.4 on 2022-12-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='user_id',
        ),
    ]
